Check for yarn
newrelic/newrelic-diagnostics-cli pull request #56
Opened 2021-01-22 16:31 UTC by punkael

# Issue

# Goals

# Implementation Details

# How to Test

2021-01-22 16:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/newrelic-diagnostics-cli?pullRequest=56) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/newrelic-diagnostics-cli?pullRequest=56) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: uturunku1<br/>:x: punkael<br/><hr/>**uturunku1** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/newrelic-diagnostics-cli?pullRequest=56) it.</sub>

2022-05-17 22:30 UTC, cade-conklin requested changes

2022-05-17 22:30 UTC, cade-conklin commented on tasks/node/env/dependencies.go
> +
If these aren't needed, the comments can be deleted

2022-05-17 22:30 UTC, cade-conklin commented
@punkael would you mind pulling in the latest changes from `develop`?

2022-05-19 18:09 UTC, daffinito commented
I updated the yarn task to use dependency injection and added tests

2022-06-06 19:20 UTC, daffinito commented
Updated the dependencies task to check for yarn if npm isn't installed.

2025-04-28 20:26 UTC, closed without merging